export const columns = [
  {
    key: 'accountType',
    label: 'Account Type',
  },
  {
    key: 'standard',
    label: 'Standard',
  },
  {
    key: 'proEcn',
    label: 'Pro-ECN',
  },
  {
    key: 'eliteEcn',
    label: 'Elice-ECN',
  },
];
type key = 'accountType' | 'standard' | 'proEcn' | 'eliteEcn';
export interface IData {
  accountType: string;
  standard: string;
  proEcn: string;
  eliteEcn: string;
  hasSup: boolean;
  hasIcon: boolean;
  sup?: string;
  supColumnKey?: key[];
  iconColumnKey?: key[];
}
export const data: IData[] = [
  {
    accountType: 'Currencies',
    standard: 'USD, EUR, GBP or SGD',
    proEcn: 'USD, EUR, GBP or SGD',
    eliteEcn: 'USD, EUR, GBP or SGD',
    hasSup: false,
    hasIcon: false,
  },
  {
    accountType: 'Leverage',
    standard: 'Upto 1:300',
    proEcn: 'Upto 1:300',
    eliteEcn: 'Upto 1:300',
    hasSup: true,
    hasIcon: false,
    sup: '(1)',
    supColumnKey: ['accountType'],
  },
  {
    accountType: 'Spread',
    standard: 'From 0.1 Pips',
    proEcn: '0* Pips',
    eliteEcn: '0* Pips',
    hasSup: false,
    hasIcon: false,
  },
  {
    accountType: 'Commission',
    standard: '0',
    proEcn: '$7/Round lot',
    eliteEcn: '0',
    hasSup: true,
    hasIcon: false,
    sup: '(3)',
    supColumnKey: ['proEcn'],
  },
  {
    accountType: 'Minimum Transaction Size',
    standard: '0.01 Lot',
    proEcn: '0.01 Lot',
    eliteEcn: '0.01 Micro Lot',
    hasSup: false,
    hasIcon: false,
  },
  {
    accountType: 'Instruments Available',
    standard: 'Forex, Metals, Shares, and Cash CFDs',
    proEcn: 'Forex, Metals, Shares, and Cash CFDs',
    eliteEcn: 'Forex, Metals, Shares, and Cash CFDs',
    hasSup: false,
    hasIcon: false,
  },
  {
    accountType: 'Stop/Limit Levels',
    standard: 'No Minimum for Forex & Metals',
    proEcn: 'No Minimum for Forex & Metals',
    eliteEcn: 'No Minimum for Forex & Metals',
    hasSup: false,
    hasIcon: false,
  },
  {
    accountType: 'Instruments Specifications',
    standard: 'View Contract Specifications',
    proEcn: 'View Contract Specifications',
    eliteEcn: 'View Contract Specifications',
    hasSup: false,
    hasIcon: false,
  },
  {
    accountType: 'Available to',
    standard: 'Globally',
    proEcn: 'Globally',
    eliteEcn: 'Globally',
    hasSup: false,
    hasIcon: false,
  },
  {
    accountType: 'Credit Bonus',
    standard: '',
    proEcn: '',
    eliteEcn: '',
    hasSup: true,
    sup: '(5)',
    supColumnKey: ['accountType'],
    hasIcon: true,
    iconColumnKey: ['standard', 'proEcn', 'eliteEcn'],
  },
  {
    accountType: 'Expert Advisor',
    standard: '',
    proEcn: '',
    eliteEcn: '',
    hasSup: false,
    hasIcon: true,
    iconColumnKey: ['standard', 'proEcn', 'eliteEcn'],
  },
  {
    accountType: 'Real Time News Feed',
    standard: '',
    proEcn: '',
    eliteEcn: '',
    hasSup: false,
    hasIcon: true,
    iconColumnKey: ['standard', 'proEcn', 'eliteEcn'],
  },
  {
    accountType: 'MT5 Mobile Trading Platform',
    standard: '',
    proEcn: '',
    eliteEcn: '',
    hasSup: false,
    hasIcon: true,
    iconColumnKey: ['standard', 'proEcn', 'eliteEcn'],
  },
  {
    accountType: 'Segregated accounts',
    standard: '',
    proEcn: '',
    eliteEcn: '',
    hasSup: false,
    hasIcon: true,
    iconColumnKey: ['standard', 'proEcn', 'eliteEcn'],
  },
  {
    accountType: 'Charts & Platforms',
    standard: '',
    proEcn: '',
    eliteEcn: '',
    hasSup: false,
    hasIcon: true,
    iconColumnKey: ['standard', 'proEcn', 'eliteEcn'],
  },
  {
    accountType: 'Free video tutorials',
    standard: '',
    proEcn: '',
    eliteEcn: '',
    hasSup: false,
    hasIcon: true,
    iconColumnKey: ['standard', 'proEcn', 'eliteEcn'],
  },
  {
    accountType: 'SMS Updates',
    standard: '',
    proEcn: '',
    eliteEcn: '',
    hasSup: false,
    hasIcon: true,
    iconColumnKey: ['standard', 'proEcn', 'eliteEcn'],
  },
  {
    accountType: 'Swap free',
    standard: '',
    proEcn: '',
    eliteEcn: '',
    hasSup: true,
    sup: '(6)',
    supColumnKey: ['accountType'],
    hasIcon: true,
    iconColumnKey: ['standard', 'proEcn', 'eliteEcn'],
  },
  {
    accountType: 'Complementary Premium Services',
    standard: '',
    proEcn: '',
    eliteEcn: '',
    hasSup: false,
    hasIcon: true,
    iconColumnKey: ['standard', 'proEcn', 'eliteEcn'],
  },
  {
    accountType: 'Execution',
    standard: 'Market Execution',
    proEcn: 'Market Execution',
    eliteEcn: 'Market Execution',
    hasSup: false,
    hasIcon: false,
  },
  {
    accountType: 'Stop out level',
    standard: '0%',
    proEcn: '0%',
    eliteEcn: '0%',
    hasSup: true,
    hasIcon: false,
    sup: '(8)',
    supColumnKey: ['accountType', 'standard', 'proEcn', 'eliteEcn'],
  },
  {
    accountType: 'Trading Platforms',
    standard: 'MT5: Windows, Mac, iOS, Android',
    proEcn: 'MT5: Windows, Mac, iOS, Android',
    eliteEcn: 'MT5: Windows, Mac, iOS, Android',
    hasSup: false,
    hasIcon: false,
  },
];
